/*
 Navicat Premium Data Transfer

 Source Server         : D2SLibData
 Source Server Type    : SQLite
 Source Server Version : 3035005 (3.35.5)
 Source Schema         : main

 Target Server Type    : SQLite
 Target Server Version : 3035005 (3.35.5)
 File Encoding         : 65001

 Date: 01/10/2023 01:04:42
*/

PRAGMA foreign_keys = false;

-- ----------------------------
-- Table structure for runes
-- ----------------------------
DROP TABLE IF EXISTS "runes";
CREATE TABLE "runes" (
  "Name" TEXT,
  "RuneName" TEXT,
  "complete" REAL,
  "firstLadderSeason" REAL,
  "lastLadderSeason" REAL,
  "PatchRelease" TEXT,
  "itype1" TEXT,
  "itype2" TEXT,
  "itype3" TEXT,
  "itype4" REAL,
  "itype5" REAL,
  "itype6" REAL,
  "etype1" REAL,
  "etype2" REAL,
  "etype3" REAL,
  "RunesUsed" TEXT,
  "Rune1" TEXT,
  "Rune2" TEXT,
  "Rune3" TEXT,
  "Rune4" TEXT,
  "Rune5" TEXT,
  "Rune6" TEXT,
  "T1Code1" TEXT,
  "T1Param1" TEXT,
  "T1Min1" REAL,
  "T1Max1" REAL,
  "T1Code2" TEXT,
  "T1Param2" TEXT,
  "T1Min2" REAL,
  "T1Max2" REAL,
  "T1Code3" TEXT,
  "T1Param3" TEXT,
  "T1Min3" REAL,
  "T1Max3" REAL,
  "T1Code4" TEXT,
  "T1Param4" TEXT,
  "T1Min4" REAL,
  "T1Max4" REAL,
  "T1Code5" TEXT,
  "T1Param5" TEXT,
  "T1Min5" REAL,
  "T1Max5" REAL,
  "T1Code6" TEXT,
  "T1Param6" TEXT,
  "T1Min6" REAL,
  "T1Max6" REAL,
  "T1Code7" TEXT,
  "T1Param7" TEXT,
  "T1Min7" REAL,
  "T1Max7" REAL,
  "eol" INTEGER,
  PRIMARY KEY ("Name")
);

-- ----------------------------
-- Records of runes
-- ----------------------------
INSERT INTO "runes" VALUES ('Runeword1', 'Ancients'' Pledge', 1.0, NULL, NULL, '109', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RalOrtTal', 'r08', 'r09', 'r07', NULL, NULL, NULL, 'res-cold', NULL, 30.0, 30.0, 'res-all', NULL, 13.0, 13.0, 'ac%', NULL, 50.0, 50.0, 'dmg-to-mana', NULL, 10.0, 10.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword2', 'Armageddon', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword3', 'Authority', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword4', 'Beast', 1.0, NULL, NULL, '110', 'axe', 'scep', 'hamm', NULL, NULL, NULL, NULL, NULL, NULL, 'BerTirUmMalLum', 'r30', 'r03', 'r22', 'r23', 'r17', NULL, 'swing2', NULL, 40.0, 40.0, 'aura', 'Fanaticism', 9.0, 9.0, 'dmg%', NULL, 240.0, 270.0, 'str', NULL, 25.0, 40.0, 'charged', 'Summon Grizzly', 5.0, 13.0, 'oskill', 'Wearbear', 3.0, 3.0, 'oskill', 'Shape Shifting', 3.0, 3.0, 0);
INSERT INTO "runes" VALUES ('Runeword5', 'Beauty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword6', 'Black', 1.0, NULL, NULL, '109', 'club', 'hamm', 'mace', NULL, NULL, NULL, NULL, NULL, NULL, 'ThulIoNef', 'r10', 'r16', 'r04', NULL, NULL, NULL, 'crush', NULL, 40.0, 40.0, 'dmg%', NULL, 120.0, 120.0, 'swing2', NULL, 15.0, 15.0, 'red-mag', NULL, 2.0, 2.0, 'att', NULL, 200.0, 200.0, 'charged', '74', 12.0, 4.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword7', 'Blood', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword8', 'Bone', 1.0, NULL, NULL, '111', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SolUmUm', 'r12', 'r22', 'r22', NULL, NULL, NULL, 'hit-skill', 'Bone Spear', 15.0, 10.0, 'gethit-skill', 'Bone Armor', 15.0, 10.0, 'nec', NULL, 2.0, 2.0, 'mana', NULL, 100.0, 150.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword9', 'Bramble', 1.0, NULL, NULL, '110', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RalOhmSurEth', 'r08', 'r27', 'r29', 'r05', NULL, NULL, 'balance2', NULL, 50.0, 50.0, 'ac', NULL, 300.0, 300.0, 'aura', 'Thorns', 15.0, 21.0, 'heal-kill', NULL, 13.0, 13.0, 'extra-pois', NULL, 25.0, 50.0, 'res-pois', NULL, 100.0, 100.0, 'charged', 'Spirit of Barbs', 33.0, 13.0, 0);
INSERT INTO "runes" VALUES ('Runeword10', 'Brand', 1.0, NULL, NULL, 'Previously Ladder Only', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'JahLoMalGul', 'r31', 'r28', 'r23', 'r25', NULL, NULL, 'dmg%', NULL, 260.0, 340.0, 'dmg-demon', NULL, 280.0, 330.0, 'hit-skill', 'Bone Spear', 100.0, 18.0, 'gethit-skill', 'Amplify Damage', 35.0, 14.0, 'knock', NULL, 1.0, 1.0, 'noheal', NULL, 1.0, 1.0, 'explosivearrow', NULL, 15.0, 15.0, 0);
INSERT INTO "runes" VALUES ('Runeword11', 'Breath of the Dying', 1.0, NULL, NULL, '110', 'weap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'VexHelElEldZodEth', 'r26', 'r15', 'r01', 'r02', 'r33', 'r05', 'swing2', NULL, 60.0, 60.0, 'dmg-undead', NULL, 125.0, 125.0, 'lifesteal', NULL, 12.0, 15.0, 'noheal', NULL, 1.0, 1.0, 'kill-skill', 'Poison Nova', 50.0, 20.0, 'dmg%', NULL, 350.0, 400.0, 'all-stats', NULL, 30.0, 30.0, 0);
INSERT INTO "runes" VALUES ('Runeword12', 'Broken Promise', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword13', 'Call to Arms', 1.0, NULL, NULL, '110', 'weap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AmnRalMalIstOhm', 'r11', 'r08', 'r23', 'r24', 'r27', NULL, 'swing2', NULL, 40.0, 40.0, 'dmg%', NULL, 200.0, 240.0, 'allskills', NULL, 1.0, 1.0, 'oskill', 'Battle Command', 2.0, 6.0, 'oskill', 'Battle Orders', 1.0, 6.0, 'oskill', 'Battle Cry', 1.0, 4.0, 'regen', NULL, 12.0, 12.0, 0);
INSERT INTO "runes" VALUES ('Runeword14', 'Chains of Honor', 1.0, NULL, NULL, '110', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DolUmBerIst', 'r14', 'r22', 'r30', 'r24', NULL, NULL, 'res-all', NULL, 50.0, 50.0, 'ac%', NULL, 70.0, 70.0, 'dmg-demon', NULL, 200.0, 200.0, 'dmg-undead', NULL, 100.0, 100.0, 'lifesteal', NULL, 8.0, 8.0, 'allskills', NULL, 2.0, 2.0, 'str', NULL, 20.0, 20.0, 0);
INSERT INTO "runes" VALUES ('Runeword15', 'Chance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword16', 'Chaos', 1.0, NULL, NULL, '110', 'h2h', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FalOhmUm', 'r19', 'r27', 'r22', NULL, NULL, NULL, 'demon-heal', NULL, 15.0, 15.0, 'dmg%', NULL, 240.0, 290.0, 'dmg-mag', NULL, 216.0, 471.0, 'oskill', 'Whirlwind', 1.0, 1.0, 'swing2', NULL, 35.0, 35.0, 'hit-skill', 'Frozen Orb', 9.0, 11.0, 'hit-skill', 'Charged Bolt', 11.0, 9.0, 0);
INSERT INTO "runes" VALUES ('Runeword17', 'Crescent Moon', 1.0, NULL, NULL, '110', 'axe', 'swor', 'pole', NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelUmTir', 'r13', 'r22', 'r03', NULL, NULL, NULL, 'pierce-ltng', NULL, 35.0, 35.0, 'ignore-ac', NULL, 1.0, 1.0, 'dmg%', NULL, 180.0, 220.0, 'abs-mag', NULL, 9.0, 11.0, 'charged', 'Summon Spirit Wolf', 30.0, 18.0, 'hit-skill', 'Static Field', 7.0, 13.0, 'hit-skill', 'Chain Lightning', 10.0, 17.0, 0);
INSERT INTO "runes" VALUES ('Runeword18', 'Darkness', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword19', 'Daylight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword20', 'Death', 1.0, NULL, NULL, 'Previously Ladder Only', 'swor', 'axe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HelElVexOrtGul', 'r15', 'r01', 'r26', 'r09', 'r25', NULL, 'dmg%', NULL, 300.0, 385.0, 'deadly/lvl', '4', NULL, NULL, 'charged', 'BloodGolem', 15.0, 22.0, 'att-skill', 'Glacial Spike', 25.0, 18.0, 'death-skill', 'Chain Lightning', 100.0, 44.0, 'crush', NULL, 50.0, 50.0, 'indestruct', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword21', 'Deception', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword22', 'Delirium', 1.0, NULL, NULL, '110', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LemIstIo', 'r20', 'r24', 'r16', NULL, NULL, NULL, 'hit-skill', 'Confuse', 11.0, 18.0, 'charged', 'Attract', 60.0, 17.0, 'gethit-skill', 'Terror', 14.0, 13.0, 'ac', NULL, 261.0, 261.0, 'gethit-skill', 'Mind Blast', 6.0, 14.0, 'gethit-skill', 'Delerium Change', 1.0, 50.0, 'allskills', NULL, 2.0, 2.0, 0);
INSERT INTO "runes" VALUES ('Runeword23', 'Desire', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword24', 'Despair', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword25', 'Destruction', 1.0, NULL, NULL, 'Previously Ladder Only', 'pole', 'swor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'VexLoBerJahKo', 'r26', 'r28', 'r30', 'r31', 'r18', NULL, 'dmg%', NULL, 350.0, 350.0, 'dmg-mag', NULL, 100.0, 180.0, 'hit-skill', 'Molten Boulder', 5.0, 23.0, 'death-skill', 'Meteor', 100.0, 45.0, 'att-skill', 'Nova', 15.0, 22.0, 'hit-skill', 'Volcano', 23.0, 12.0, 'noheal', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword26', 'Doom', 1.0, NULL, NULL, '110', 'axe', 'pole', 'hamm', NULL, NULL, NULL, NULL, NULL, NULL, 'HelOhmUmLoCham', 'r15', 'r27', 'r22', 'r28', 'r32', NULL, 'dmg%', NULL, 280.0, 320.0, 'aura', 'Holy Freeze', 12.0, 12.0, 'swing2', NULL, 45.0, 45.0, 'noheal', NULL, 1.0, 1.0, 'pierce-cold', NULL, 40.0, 60.0, 'allskills', NULL, 2.0, 2.0, 'hit-skill', 'Volcano', 5.0, 18.0, 0);
INSERT INTO "runes" VALUES ('Runeword27', 'Dragon', 1.0, NULL, NULL, 'Previously Ladder Only', 'tors', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SurLoSol', 'r29', 'r28', 'r12', NULL, NULL, NULL, 'ac', NULL, 360.0, 360.0, 'ac-miss', NULL, 230.0, 230.0, 'str/lvl', '3', NULL, NULL, 'hit-skill', 'Hydra', 12.0, 15.0, 'gethit-skill', 'Venom', 20.0, 18.0, 'aura', 'Holy Fire', 14.0, 14.0, 'all-stats', NULL, 3.0, 5.0, 0);
INSERT INTO "runes" VALUES ('Runeword28', 'Dread', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword29', 'Dream', 1.0, NULL, NULL, 'Previously Ladder Only', 'helm', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'IoJahPul', 'r16', 'r31', 'r21', NULL, NULL, NULL, 'ac', NULL, 150.0, 220.0, 'gethit-skill', 'Confuse', 10.0, 15.0, 'mana/lvl', '5', NULL, NULL, 'res-all', NULL, 5.0, 20.0, 'balance3', NULL, 20.0, 30.0, 'aura', 'Holy Shock', 15.0, 15.0, 'mag%', NULL, 12.0, 25.0, 0);
INSERT INTO "runes" VALUES ('Runeword30', 'Duress', 1.0, NULL, NULL, '110', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelUmThul', 'r13', 'r22', 'r10', NULL, NULL, NULL, 'dmg-cold', '50', 37.0, 133.0, 'dmg%', NULL, 10.0, 20.0, 'ac%', NULL, 150.0, 200.0, 'balance2', NULL, 20.0, 20.0, 'openwounds', NULL, 33.0, 33.0, 'crush', NULL, 15.0, 15.0, 'stamdrain', NULL, -20.0, -20.0, 0);
INSERT INTO "runes" VALUES ('Runeword31', 'Edge', 1.0, NULL, NULL, 'Previously Ladder Only', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TirTalAmn', 'r03', 'r07', 'r11', NULL, NULL, NULL, 'dmg-demon', NULL, 320.0, 380.0, 'dmg-undead', NULL, 280.0, 280.0, 'swing2', NULL, 35.0, 35.0, 'noheal', NULL, 1.0, 1.0, 'aura', 'Thorns', 15.0, 15.0, 'all-stats', NULL, 5.0, 10.0, 'cheap', NULL, 15.0, 15.0, 0);
INSERT INTO "runes" VALUES ('Runeword32', 'Elation', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword33', 'Enigma', 1.0, NULL, NULL, '110', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'JahIthBer', 'r31', 'r06', 'r30', NULL, NULL, NULL, 'ac', NULL, 750.0, 775.0, 'heal-kill', NULL, 14.0, 14.0, 'move2', NULL, 45.0, 45.0, 'str/lvl', '6', NULL, NULL, 'allskills', NULL, 2.0, 2.0, 'mag%/lvl', '8', NULL, NULL, 'oskill', 'Teleport', 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword34', 'Enlightenment', 1.0, NULL, NULL, '111', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PulRalSur', 'r21', 'r08', 'r12', NULL, NULL, NULL, 'hit-skill', 'Fire Ball', 5.0, 15.0, 'gethit-skill', 'Blaze', 5.0, 15.0, 'sor', NULL, 2.0, 2.0, 'oskill', 'Warmth', 1.0, 1.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword35', 'Envy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword36', 'Eternity', 1.0, NULL, NULL, '110', 'mele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AmnBerIstSolSur', 'r11', 'r30', 'r24', 'r12', 'r29', NULL, 'dmg%', NULL, 260.0, 310.0, 'indestruct', NULL, 1.0, 1.0, 'slow', NULL, 33.0, 33.0, 'charged', 'Revive', 88.0, 8.0, 'regen', NULL, 16.0, 16.0, 'regen-mana', NULL, 16.0, 16.0, 'nofreeze', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword37', 'Exile', 1.0, NULL, NULL, '110', 'pala', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'VexOhmIstDol', 'r26', 'r27', 'r24', 'r14', NULL, NULL, 'block2', NULL, 30.0, 30.0, 'freeze', NULL, 1.0, 1.0, 'ac%', NULL, 220.0, 260.0, 'aura', 'Defiance', 13.0, 16.0, 'skilltab', '10', 2.0, 2.0, 'hit-skill', 'Life Tap', 15.0, 5.0, 'rep-dur', '25', NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword38', 'Faith', 1.0, NULL, NULL, '110, Previously Ladder Only', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'OhmJahLemEld', 'r27', 'r31', 'r20', 'r02', NULL, NULL, 'dmg%', NULL, 280.0, 280.0, 'att%', NULL, 300.0, 300.0, 'dmg-fire', NULL, 120.0, 120.0, 'res-all', NULL, 15.0, 15.0, 'aura', 'Fanaticism', 12.0, 15.0, 'reanimate', '1', 10.0, 10.0, 'allskills', NULL, 1.0, 2.0, 0);
INSERT INTO "runes" VALUES ('Runeword39', 'Famine', 1.0, NULL, NULL, NULL, 'axe', 'hamm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FalOhmOrtJah', 'r19', 'r27', 'r09', 'r31', NULL, NULL, 'dmg%', NULL, 270.0, 320.0, 'lifesteal', NULL, 12.0, 12.0, 'swing2', NULL, 30.0, 30.0, 'noheal', NULL, 1.0, 1.0, 'dmg-mag', NULL, 180.0, 200.0, 'dmg-elem', NULL, 50.0, 200.0, 'ethereal', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword40', 'Flickering Flame', 1.0, 1.0, 2.0, 'D2R Ladder 1', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NefPulVex', 'r04', 'r21', 'r26', NULL, NULL, NULL, 'fireskill', NULL, 3.0, 3.0, 'aura', 'Resist Fire', 4.0, 8.0, 'pierce-fire', NULL, 10.0, 15.0, 'mana', NULL, 50.0, 75.0, 'half-freeze', NULL, 1.0, 1.0, 'res-pois-len', NULL, 50.0, 50.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword41', 'Fortitude', 1.0, NULL, NULL, 'Previously Ladder Only', 'weap', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ElSolDolLo', 'r01', 'r12', 'r14', 'r28', NULL, NULL, 'ac%', NULL, 200.0, 200.0, 'dmg%', NULL, 300.0, 300.0, 'cast3', NULL, 25.0, 25.0, 'gethit-skill', 'Chilling Armor', 20.0, 15.0, 'dmg-to-mana', NULL, 12.0, 12.0, 'hp/lvl', NULL, 8.0, 12.0, 'res-all', NULL, 25.0, 30.0, 0);
INSERT INTO "runes" VALUES ('Runeword42', 'Fortune', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword43', 'Amity', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword44', 'Fury', 1.0, NULL, NULL, '109', 'mele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'JahGulEth', 'r31', 'r25', 'r05', NULL, NULL, NULL, 'dmg%', NULL, 209.0, 209.0, 'swing2', NULL, 40.0, 40.0, 'noheal', NULL, 1.0, 1.0, 'openwounds', NULL, 66.0, 66.0, 'lifesteal', NULL, 6.0, 6.0, 'deadly', NULL, 33.0, 33.0, 'skill', '147', 5.0, 5.0, 0);
INSERT INTO "runes" VALUES ('Runeword45', 'Gloom', 1.0, NULL, NULL, '110', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FalUmPul', 'r19', 'r22', 'r21', NULL, NULL, NULL, 'ac%', NULL, 170.0, 230.0, 'res-all', NULL, 30.0, 30.0, 'gethit-skill', 'Dim Vision', 15.0, 3.0, 'balance2', NULL, 10.0, 10.0, 'dmg-to-mana', NULL, 5.0, 5.0, 'light', NULL, -3.0, -3.0, 'half-freeze', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword46', 'Glory', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword47', 'Grief', 1.0, NULL, NULL, 'Previously Ladder Only', 'swor', 'axe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EthTirLoMalRal', 'r05', 'r03', 'r28', 'r23', 'r08', NULL, 'dmg-dem/lvl', '15', NULL, NULL, 'dmg', NULL, 340.0, 400.0, 'swing3', NULL, 30.0, 40.0, 'hit-skill', 'Venom', 35.0, 15.0, 'pierce-pois', NULL, 20.0, 25.0, 'ignore-ac', NULL, 1.0, 1.0, 'heal-kill', NULL, 10.0, 15.0, 0);
INSERT INTO "runes" VALUES ('Runeword48', 'Hand of Justice', 1.0, NULL, NULL, '110', 'weap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SurChamAmnLo', 'r29', 'r32', 'r11', 'r28', NULL, NULL, 'swing2', NULL, 33.0, 33.0, 'dmg%', NULL, 280.0, 330.0, 'aura', 'Holy Fire', 16.0, 16.0, 'levelup-skill', 'Blaze', 100.0, 36.0, 'death-skill', 'Meteor', 100.0, 48.0, 'ignore-ac', NULL, 1.0, 1.0, 'pierce-fire', NULL, 20.0, 20.0, 0);
INSERT INTO "runes" VALUES ('Runeword49', 'Harmony', 1.0, NULL, NULL, 'Previously Ladder Only', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TirIthSolKo', 'r03', 'r06', 'r12', 'r18', NULL, NULL, 'dmg%', NULL, 200.0, 275.0, 'dmg-elem', NULL, 55.0, 160.0, 'charged', 'Revive', 25.0, 20.0, 'aura', 'Vigor', 10.0, 10.0, 'oskill', 'Valkyrie', 2.0, 6.0, 'regen-mana', NULL, 20.0, 20.0, 'light', NULL, 2.0, 2.0, 0);
INSERT INTO "runes" VALUES ('Runeword50', 'Hatred', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword51', 'Heart of the Oak', 1.0, NULL, NULL, '110', 'staf', 'mace', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'KoVexPulThul', 'r18', 'r26', 'r21', 'r10', NULL, NULL, 'cast2', NULL, 40.0, 40.0, 'charged', 'Oak Sage', 25.0, 4.0, 'mana%', NULL, 15.0, 15.0, 'allskills', NULL, 3.0, 3.0, 'regen', NULL, 20.0, 20.0, 'res-all', NULL, 30.0, 40.0, 'charged', 'Raven', 60.0, 14.0, 0);
INSERT INTO "runes" VALUES ('Runeword52', 'Heaven''s Will', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword53', 'Holy Tears', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword54', 'Holy Thunder', 1.0, NULL, NULL, '109', 'scep', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EthRalOrtTal', 'r05', 'r08', 'r09', 'r07', NULL, NULL, 'dmg%', NULL, 60.0, 60.0, 'dmg-ltng', NULL, 20.0, 60.0, 'dmg-max', NULL, 10.0, 10.0, 'res-ltng', NULL, 60.0, 60.0, 'res-ltng-max', NULL, 5.0, 5.0, 'skill', '118', 3.0, 3.0, 'charged', '53', 60.0, 7.0, 0);
INSERT INTO "runes" VALUES ('Runeword55', 'Honor', 1.0, NULL, NULL, '109', 'mele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AmnElIthTirSol', 'r11', 'r01', 'r06', 'r03', 'r12', NULL, 'dmg%', NULL, 160.0, 160.0, 'regen', NULL, 10.0, 10.0, 'allskills', NULL, 1.0, 1.0, 'att', NULL, 200.0, 200.0, 'deadly', NULL, 25.0, 25.0, 'str', NULL, 10.0, 10.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword56', 'Revenge', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword57', 'Humility', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword58', 'Hunger', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword59', 'Ice', 1.0, NULL, NULL, 'Previously Ladder Only', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AmnShaelJahLo', 'r11', 'r13', 'r31', 'r28', NULL, NULL, 'dmg%', NULL, 140.0, 210.0, 'aura', 'Holy Freeze', 18.0, 18.0, 'extra-cold', NULL, 25.0, 30.0, 'hit-skill', 'Frost Nova', 25.0, 22.0, 'levelup-skill', 'Blizzard', 100.0, 40.0, 'pierce-cold', NULL, 20.0, 20.0, 'gold%/lvl', '25', NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword60', 'Infinity', 1.0, NULL, NULL, 'Previously Ladder Only', 'pole', 'spea', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BerMalBerIst', 'r30', 'r23', 'r30', 'r24', NULL, NULL, 'dmg%', NULL, 255.0, 325.0, 'move3', NULL, 35.0, 35.0, 'vit/lvl', '4', NULL, NULL, 'aura', 'Conviction', 12.0, 12.0, 'kill-skill', 'Chain Lightning', 50.0, 20.0, 'pierce-ltng', NULL, 45.0, 55.0, 'charged', 'Cyclone Armor', 30.0, 21.0, 0);
INSERT INTO "runes" VALUES ('Runeword61', 'Innocence', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword62', 'Insight', 1.0, NULL, NULL, 'Previously Ladder Only', 'pole', 'staf', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, 'RalTirTalSol', 'r08', 'r03', 'r07', 'r12', NULL, NULL, 'dmg%', NULL, 200.0, 260.0, 'att%', NULL, 180.0, 250.0, 'mag%', NULL, 23.0, 23.0, 'oskill', 'Critical Strike', 1.0, 6.0, 'cast2', NULL, 35.0, 35.0, 'aura', 'Meditation', 12.0, 17.0, 'all-stats', NULL, 5.0, 5.0, 0);
INSERT INTO "runes" VALUES ('Runeword63', 'Jealousy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword64', 'Judgment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword65', 'King''s Grace', 1.0, NULL, NULL, '109', 'swor', 'scep', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AmnRalThul', 'r11', 'r08', 'r10', NULL, NULL, NULL, 'dmg%', NULL, 100.0, 100.0, 'att', NULL, 150.0, 150.0, 'dmg-demon', NULL, 100.0, 100.0, 'dmg-undead', NULL, 50.0, 50.0, 'att-demon', NULL, 100.0, 100.0, 'att-undead', NULL, 100.0, 100.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword66', 'Kingslayer', 1.0, NULL, NULL, '110', 'swor', 'axe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MalUmGulFal', 'r23', 'r22', 'r25', 'r19', NULL, NULL, 'swing2', NULL, 30.0, 30.0, 'dmg%', NULL, 230.0, 270.0, 'reduce-ac', NULL, 25.0, 25.0, 'crush', NULL, 33.0, 33.0, 'openwounds', NULL, 25.0, 25.0, 'oskill', 'Vengeance', 1.0, 1.0, 'gold%', NULL, 40.0, 40.0, 0);
INSERT INTO "runes" VALUES ('Runeword67', 'Knight''s Vigil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword68', 'Knowledge', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword69', 'Last Wish', 1.0, NULL, NULL, 'Previously Ladder Only', 'swor', 'hamm', 'axe', NULL, NULL, NULL, NULL, NULL, NULL, 'JahMalJahSurJahBer', 'r31', 'r23', 'r31', 'r29', 'r31', 'r30', 'dmg%', NULL, 330.0, 375.0, 'att-skill', 'Charged Bolt', 20.0, 20.0, 'hit-skill', 'Life Tap', 10.0, 18.0, 'gethit-skill', 'Fade', 6.0, 11.0, 'crush', NULL, 40.0, 50.0, 'mag%/lvl', '4', NULL, NULL, 'aura', 'Might', 17.0, 17.0, 0);
INSERT INTO "runes" VALUES ('Runeword70', 'Law', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword71', 'Lawbringer', 1.0, NULL, NULL, 'Previously Ladder Only', 'swor', 'hamm', 'scep', NULL, NULL, NULL, NULL, NULL, NULL, 'AmnLemKo', 'r11', 'r20', 'r18', NULL, NULL, NULL, 'dmg-cold', NULL, 130.0, 180.0, 'dmg-fire', NULL, 150.0, 210.0, 'aura', 'Sanctuary', 16.0, 18.0, 'hit-skill', 'Decrepify', 20.0, 15.0, 'ac-miss', NULL, 200.0, 250.0, 'rip', NULL, 1.0, 1.0, 'reduce-ac', NULL, 50.0, 50.0, 0);
INSERT INTO "runes" VALUES ('Runeword72', 'Leaf', 1.0, NULL, NULL, '109', 'staf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TirRal', 'r03', 'r08', NULL, NULL, NULL, NULL, 'fireskill', NULL, 3.0, 3.0, 'ac/lvl', NULL, 16.0, 16.0, 'res-cold', NULL, 33.0, 33.0, 'skill', '41', 3.0, 3.0, 'skill', '36', 3.0, 3.0, 'skill', '37', 3.0, 3.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword73', 'Lightning', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword74', 'Lionheart', 1.0, NULL, NULL, '109', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HelLumFal', 'r15', 'r17', 'r19', NULL, NULL, NULL, 'str', NULL, 15.0, 15.0, 'vit', NULL, 20.0, 20.0, 'dex', NULL, 15.0, 15.0, 'dmg%', NULL, 20.0, 20.0, 'hp', NULL, 50.0, 50.0, 'res-all', NULL, 30.0, 30.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword75', 'Lore', 1.0, NULL, NULL, '109', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'OrtSol', 'r09', 'r12', NULL, NULL, NULL, NULL, 'enr', NULL, 10.0, 10.0, 'allskills', NULL, 1.0, 1.0, 'light', NULL, 2.0, 2.0, 'mana-kill', NULL, 2.0, 2.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword76', 'Love', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword77', 'Loyalty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword78', 'Lust', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword79', 'Madness', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword81', 'Malice', 1.0, NULL, NULL, '109', 'mele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'IthElEth', 'r06', 'r01', 'r05', NULL, NULL, NULL, 'openwounds', NULL, 100.0, 100.0, 'dmg-ac', NULL, -100.0, -100.0, 'noheal', NULL, 1.0, 1.0, 'dmg%', NULL, 33.0, 33.0, 'light', NULL, -1.0, -1.0, 'regen', NULL, -5.0, -5.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword82', 'Melody', 1.0, NULL, NULL, '109', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelKoNef', 'r13', 'r18', 'r04', NULL, NULL, NULL, 'dmg%', NULL, 50.0, 50.0, 'skilltab', '0', 3.0, 3.0, 'skill', '9', 3.0, 3.0, 'skill', '13', 3.0, 3.0, 'skill', '17', 3.0, 3.0, 'dmg-undead', NULL, 300.0, 300.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword83', 'Memory', 1.0, NULL, NULL, '109', 'staf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LumIoSolEth', 'r17', 'r16', 'r12', 'r05', NULL, NULL, 'mana%', NULL, 20.0, 20.0, 'red-mag', NULL, 7.0, 7.0, 'ac%', NULL, 50.0, 50.0, 'cast2', NULL, 33.0, 33.0, 'sor', NULL, 3.0, 3.0, 'skill', '58', 3.0, 3.0, 'skill', '42', 2.0, 2.0, 0);
INSERT INTO "runes" VALUES ('Runeword84', 'Mist', 1.0, 1.0, 2.0, 'D2R Ladder 1', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ChamShaelGulThulIth', 'r32', 'r13', 'r25', 'r10', 'r06', NULL, 'allskills', NULL, 3.0, 3.0, 'dmg%', NULL, 325.0, 375.0, 'aura', 'Concentration', 8.0, 12.0, 'pierce', NULL, 100.0, 100.0, 'vit', NULL, 24.0, 24.0, 'res-all', NULL, 40.0, 40.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword85', 'Morning', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword86', 'Mystery', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword87', 'Myth', 1.0, NULL, NULL, '111', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HelAmnNef', 'r15', 'r11', 'r04', NULL, NULL, NULL, 'hit-skill', 'Taunt', 10.0, 1.0, 'gethit-skill', 'Howl', 3.0, 1.0, 'bar', NULL, 2.0, 2.0, 'regen', NULL, 10.0, 10.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword88', 'Nadir', 1.0, NULL, NULL, '109', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NefTir', 'r04', 'r03', NULL, NULL, NULL, NULL, 'ac%', NULL, 50.0, 50.0, 'ac', NULL, 10.0, 10.0, 'light', NULL, -3.0, -3.0, 'charged', '264', 9.0, 13.0, 'gold%', NULL, -33.0, -33.0, 'str', NULL, 5.0, 5.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword89', 'Nature''s Kingdom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword90', 'Night', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword91', 'Oath', 1.0, NULL, NULL, 'Previously Ladder Only', 'swor', 'axe', 'mace', NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelPulMalLum', 'r13', 'r21', 'r23', 'r17', NULL, NULL, 'dmg%', NULL, 210.0, 340.0, 'swing1', NULL, 30.0, 30.0, 'hit-skill', 'Bone Spirit', 30.0, 20.0, 'charged', 'IronGolem', 14.0, 17.0, 'charged', 'Heart of Wolverine', 20.0, 16.0, 'abs-mag', NULL, 10.0, 15.0, 'indestruct', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword92', 'Obedience', 1.0, NULL, NULL, 'Previously Ladder Only', 'pole', 'spea', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HelKoThulEthFal', 'r15', 'r18', 'r10', 'r05', 'r19', NULL, 'dmg%', NULL, 370.0, 370.0, 'crush', NULL, 40.0, 40.0, 'kill-skill', 'enchant', 30.0, 21.0, 'pierce-fire', NULL, 25.0, 25.0, 'ac', NULL, 200.0, 300.0, 'balance3', NULL, 40.0, 40.0, 'res-all', NULL, 20.0, 30.0, 0);
INSERT INTO "runes" VALUES ('Runeword93', 'Oblivion', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword94', 'Obsession', 1.0, 1.0, 2.0, 'D2R Ladder 1', 'staf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ZodIstLemLumIoNef', 'r33', 'r24', 'r20', 'r17', 'r16', 'r04', 'allskills', NULL, 4.0, 4.0, 'gethit-skill', 'Weaken', 24.0, 10.0, 'cast3', NULL, 65.0, 65.0, 'balance3', NULL, 60.0, 60.0, 'res-all', NULL, 60.0, 70.0, 'hp%', NULL, 15.0, 25.0, 'regen-mana', NULL, 15.0, 30.0, 0);
INSERT INTO "runes" VALUES ('Runeword95', 'Passion', 1.0, NULL, NULL, '110', 'weap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DolOrtEldLem', 'r14', 'r09', 'r02', 'r20', NULL, NULL, 'dmg%', NULL, 160.0, 210.0, 'oskill', 'Zeal', 1.0, 1.0, 'att%', NULL, 50.0, 80.0, 'oskill', 'Berserk', 1.0, 1.0, 'swing2', NULL, 25.0, 25.0, 'charged', 'Heart of Wolverine', 12.0, 3.0, 'stupidity', NULL, 10.0, 10.0, 0);
INSERT INTO "runes" VALUES ('Runeword96', 'Patience', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword97', 'Pattern', 1.0, 1.0, 2.0, 'D2R Ladder 1', 'h2h', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TalOrtThul', 'r07', 'r09', 'r10', NULL, NULL, NULL, 'att%', NULL, 10.0, 10.0, 'dmg%', NULL, 40.0, 80.0, 'dmg-fire', NULL, 12.0, 32.0, 'res-all', NULL, 15.0, 15.0, 'str', NULL, 6.0, 6.0, 'dex', NULL, 6.0, 6.0, 'block2', NULL, 30.0, 30.0, 0);
INSERT INTO "runes" VALUES ('Runeword98', 'Peace', 1.0, NULL, NULL, '111', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelThulAmn', 'r13', 'r10', 'r11', NULL, NULL, NULL, 'hit-skill', 'Valkyrie', 2.0, 15.0, 'gethit-skill', 'Slow Missiles', 4.0, 5.0, 'ama', NULL, 2.0, 2.0, 'oskill', 'Critical Strike', 2.0, 2.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword99', 'Voice of Reason', 1.0, NULL, NULL, 'Previously Ladder Only', 'swor', 'mace', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LemKoElEld', 'r20', 'r18', 'r01', 'r02', NULL, NULL, 'dmg-demon', NULL, 220.0, 350.0, 'dmg-undead', NULL, 280.0, 300.0, 'dmg-cold', NULL, 100.0, 220.0, 'pierce-cold', NULL, 24.0, 24.0, 'hit-skill', 'Ice Blast', 18.0, 20.0, 'hit-skill', 'Frozen Orb', 15.0, 13.0, 'nofreeze', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword100', 'Penitence', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword101', 'Peril', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword102', 'Pestilence', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword103', 'Phoenix', 1.0, NULL, NULL, 'Previously Ladder Only', 'weap', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'VexVexLoJah', 'r26', 'r26', 'r28', 'r31', NULL, NULL, 'dmg%', NULL, 350.0, 400.0, 'ac-miss', NULL, 350.0, 400.0, 'hit-skill', 'Firestorm', 40.0, 22.0, 'levelup-skill', 'Blaze', 100.0, 40.0, 'pierce-fire', NULL, 28.0, 28.0, 'aura', 'Redemption', 10.0, 15.0, 'abs-fire', NULL, 15.0, 21.0, 0);
INSERT INTO "runes" VALUES ('Runeword104', 'Piety', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword105', 'Pillar of Faith', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword106', 'Plague', 1.0, 1.0, 2.0, 'D2R Ladder 1', 'swor', 'knif', 'h2h', NULL, NULL, NULL, NULL, NULL, NULL, 'ChamShaelUm', 'r32', 'r13', 'r22', NULL, NULL, NULL, 'dmg%', NULL, 220.0, 320.0, 'gethit-skill', 'Lower Resist', 20.0, 12.0, 'hit-skill', 'Poison Nova', 25.0, 15.0, 'pierce-pois', NULL, 23.0, 23.0, 'deadly/lvl', '3', NULL, NULL, 'aura', 'Cleansing', 13.0, 17.0, 'allskills', NULL, 1.0, 2.0, 0);
INSERT INTO "runes" VALUES ('Runeword107', 'Praise', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword108', 'Prayer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword109', 'Pride', 1.0, NULL, NULL, 'Previously Ladder Only', 'pole', 'spea', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ChamSurIoLo', 'r32', 'r29', 'r16', 'r28', NULL, NULL, 'dmg-dem/lvl', '8', NULL, NULL, 'dmg-ltng', NULL, 50.0, 280.0, 'att%', NULL, 260.0, 300.0, 'aura', 'Concentration', 16.0, 20.0, 'gethit-skill', 'Fire Wall', 25.0, 17.0, 'regen', NULL, 8.0, 8.0, 'gold%/lvl', '15', NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword110', 'Principle', 1.0, NULL, NULL, '111', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RalGulEld', 'r08', 'r25', 'r02', NULL, NULL, NULL, 'hit-skill', 'Holy Bolt', 100.0, 5.0, 'pal', NULL, 2.0, 2.0, 'hp', NULL, 100.0, 150.0, 'dmg-undead', NULL, 50.0, 50.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword111', 'Prowess in Battle', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword112', 'Prudence', 1.0, NULL, NULL, '110', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MalTir', 'r23', 'r03', NULL, NULL, NULL, NULL, 'ac%', NULL, 140.0, 170.0, 'red-mag', NULL, 10.0, 10.0, 'red-dmg', NULL, 3.0, 3.0, 'res-all', NULL, 25.0, 35.0, 'balance2', NULL, 25.0, 25.0, 'rep-dur', '25', NULL, NULL, 'light', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword113', 'Punishment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword114', 'Purity', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword115', 'Question', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword116', 'Radiance', 1.0, NULL, NULL, '109', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NefSolIth', 'r04', 'r12', 'r06', NULL, NULL, NULL, 'light', NULL, 5.0, 5.0, 'enr', NULL, 10.0, 10.0, 'vit', NULL, 10.0, 10.0, 'red-mag', NULL, 3.0, 3.0, 'mana', NULL, 33.0, 33.0, 'ac%', NULL, 75.0, 75.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword117', 'Rain', 1.0, NULL, NULL, '111', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'OrtMalIth', 'r09', 'r23', 'r06', NULL, NULL, NULL, 'hit-skill', 'Twister', 5.0, 15.0, 'gethit-skill', 'Cyclone Armor', 5.0, 15.0, 'dru', NULL, 2.0, 2.0, 'mana', NULL, 100.0, 150.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword118', 'Reason', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword119', 'Red', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword120', 'Rhyme', 1.0, NULL, NULL, '109', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelEth', 'r13', 'r05', NULL, NULL, NULL, NULL, 'block2', NULL, 20.0, 20.0, 'block', NULL, 20.0, 20.0, 'res-all', NULL, 25.0, 25.0, 'nofreeze', NULL, 1.0, 1.0, 'gold%', NULL, 50.0, 50.0, 'mag%', NULL, 25.0, 25.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword121', 'Rift', 1.0, NULL, NULL, 'Previously Ladder Only', 'pole', 'scep', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HelKoLemGul', 'r15', 'r18', 'r20', 'r25', NULL, NULL, 'dmg-mag', NULL, 160.0, 250.0, 'dmg-fire', NULL, 60.0, 180.0, 'dmg-to-mana', NULL, 38.0, 38.0, 'hit-skill', 'Tornado', 20.0, 16.0, 'att-skill', 'Frozen Orb', 16.0, 21.0, 'charged', 'Iron Maiden', 40.0, 15.0, 'all-stats', NULL, 5.0, 10.0, 0);
INSERT INTO "runes" VALUES ('Runeword122', 'Sanctuary', 1.0, NULL, NULL, '110', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'KoKoMal', 'r18', 'r18', 'r23', NULL, NULL, NULL, 'block', NULL, 20.0, 20.0, 'block2', NULL, 20.0, 20.0, 'ac%', NULL, 130.0, 160.0, 'ac-miss', NULL, 250.0, 250.0, 'res-all', NULL, 50.0, 70.0, 'balance2', NULL, 20.0, 20.0, 'charged', 'Slow Missiles', 60.0, 12.0, 0);
INSERT INTO "runes" VALUES ('Runeword123', 'Serendipity', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword124', 'Shadow', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword125', 'Shadow of Doubt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword126', 'Silence', 1.0, NULL, NULL, '109', 'weap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DolEldHelIstTirVex', 'r14', 'r02', 'r15', 'r24', 'r03', 'r26', 'manasteal', NULL, 4.0, 4.0, 'stupidity', NULL, 33.0, 33.0, 'dmg%', NULL, 200.0, 200.0, 'swing2', NULL, 20.0, 20.0, 'res-all', NULL, 75.0, 75.0, 'allskills', NULL, 2.0, 2.0, 'balance2', NULL, 20.0, 20.0, 0);
INSERT INTO "runes" VALUES ('Runeword127', 'Siren''s Song', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword128', 'Smoke', 1.0, NULL, NULL, '109', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NefLum', 'r04', 'r17', NULL, NULL, NULL, NULL, 'ac-miss', NULL, 250.0, 250.0, 'ac%', NULL, 75.0, 75.0, 'res-all', NULL, 50.0, 50.0, 'balance2', NULL, 20.0, 20.0, 'light', NULL, -1.0, -1.0, 'charged', '72', 18.0, 6.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword129', 'Sorrow', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword130', 'Spirit', 1.0, NULL, NULL, 'Previously Ladder Only', 'swor', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TalThulOrtAmn', 'r07', 'r10', 'r09', 'r11', NULL, NULL, 'balance3', NULL, 55.0, 55.0, 'mana', NULL, 89.0, 112.0, 'ac-miss', NULL, 250.0, 250.0, 'vit', NULL, 22.0, 22.0, 'cast3', NULL, 25.0, 35.0, 'abs-mag', NULL, 3.0, 8.0, 'allskills', NULL, 2.0, 2.0, 0);
INSERT INTO "runes" VALUES ('Runeword131', 'Splendor', 1.0, NULL, NULL, '110', 'shld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EthLum', 'r05', 'r17', NULL, NULL, NULL, NULL, 'light', NULL, 3.0, 3.0, 'gold%', NULL, 50.0, 50.0, 'mag%', NULL, 20.0, 20.0, 'ac%', NULL, 60.0, 100.0, 'block2', NULL, 20.0, 20.0, 'cast2', NULL, 10.0, 10.0, 'allskills', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword132', 'Starlight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword133', 'Stealth', 1.0, NULL, NULL, '109', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TalEth', 'r07', 'r05', NULL, NULL, NULL, NULL, 'red-mag', NULL, 3.0, 3.0, 'dex', NULL, 6.0, 6.0, 'stam', NULL, 15.0, 15.0, 'move2', NULL, 25.0, 25.0, 'cast2', NULL, 25.0, 25.0, 'balance2', NULL, 25.0, 25.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword134', 'Steel', 1.0, NULL, NULL, '109', 'swor', 'axe', 'mace', NULL, NULL, NULL, NULL, NULL, NULL, 'TirEl', 'r03', 'r01', NULL, NULL, NULL, NULL, 'swing2', NULL, 25.0, 25.0, 'dmg-min', NULL, 3.0, 3.0, 'dmg-max', NULL, 3.0, 3.0, 'openwounds', NULL, 50.0, 50.0, 'dmg%', NULL, 20.0, 20.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword135', 'Still Water', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword136', 'Sting', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword137', 'Stone', 1.0, NULL, NULL, '110', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelUmPulLum', 'r13', 'r22', 'r21', 'r17', NULL, NULL, 'ac%', NULL, 220.0, 260.0, 'charged', 'Clay Golem', 16.0, 16.0, 'ac-miss', NULL, 300.0, 300.0, 'charged', 'Molten Boulder', 80.0, 16.0, 'str', NULL, 16.0, 16.0, 'vit', NULL, 16.0, 16.0, 'balance2', NULL, 40.0, 40.0, 0);
INSERT INTO "runes" VALUES ('Runeword138', 'Storm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword139', 'Strength', 1.0, NULL, NULL, '109', 'mele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AmnTir', 'r11', 'r03', NULL, NULL, NULL, NULL, 'str', NULL, 20.0, 20.0, 'dmg%', NULL, 35.0, 35.0, 'vit', NULL, 10.0, 10.0, 'crush', NULL, 25.0, 25.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword140', 'Tempest', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword141', 'Temptation', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword142', 'Terror', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword143', 'Thirst', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword144', 'Thought', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword145', 'Thunder', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword146', 'Time', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword147', 'Tradition', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword148', 'Treachery', 1.0, NULL, NULL, '111', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelThulLem', 'r13', 'r10', 'r20', NULL, NULL, NULL, 'hit-skill', 'Venom', 25.0, 15.0, 'gethit-skill', 'Fade', 5.0, 15.0, 'ass', NULL, 2.0, 2.0, 'swing2', NULL, 45.0, 45.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword149', 'Trust', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword150', 'Truth', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword151', 'Unbending Will', 1.0, 1.0, 2.0, 'D2R Ladder 1', 'swor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FalIoIthEldElHel', 'r19', 'r16', 'r06', 'r02', 'r01', 'r15', 'skilltab', '12', 3.0, 3.0, 'hit-skill', 'Taunt', 18.0, 18.0, 'swing2', NULL, 20.0, 30.0, 'dmg%', NULL, 300.0, 350.0, 'red-dmg', NULL, 8.0, 8.0, 'noheal', NULL, 1.0, 1.0, 'lifesteal', NULL, 8.0, 10.0, 0);
INSERT INTO "runes" VALUES ('Runeword152', 'Valor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword153', 'Vengeance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword154', 'Venom', 1.0, NULL, NULL, '109', 'weap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TalDolMal', 'r07', 'r14', 'r23', NULL, NULL, NULL, 'dmg-pois', '175', 312.0, 312.0, 'ignore-ac', NULL, 1.0, 1.0, 'charged', '83', 27.0, 15.0, 'charged', '92', 11.0, 13.0, 'manasteal', NULL, 7.0, 7.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword155', 'Victory', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword156', 'Voice', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword157', 'Void', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword158', 'War', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword159', 'Water', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword160', 'Wealth', 1.0, NULL, NULL, '109', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LmKoTir', 'r20', 'r18', 'r03', NULL, NULL, NULL, 'gold%', NULL, 250.0, 250.0, 'mag%', NULL, 100.0, 100.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword161', 'Whisper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword162', 'White', 1.0, NULL, NULL, '109', 'wand', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DolIo', 'r14', 'r16', NULL, NULL, NULL, NULL, 'skilltab', '7', 3.0, 3.0, 'red-mag', NULL, 4.0, 4.0, 'cast2', NULL, 20.0, 20.0, 'mana', NULL, 13.0, 13.0, 'skill', '68', 3.0, 3.0, 'skill', '84', 2.0, 2.0, 'skill', '69', 4.0, 4.0, 0);
INSERT INTO "runes" VALUES ('Runeword163', 'Wind', 1.0, NULL, NULL, '110', 'mele', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SurEl', 'r29', 'r01', NULL, NULL, NULL, NULL, 'dmg%', NULL, 120.0, 160.0, 'swing2', NULL, 40.0, 40.0, 'move2', NULL, 20.0, 20.0, 'reduce-ac', NULL, 50.0, 50.0, 'hit-skill', 'Tornado', 10.0, 9.0, 'charged', '240', 127.0, 13.0, 'balance2', NULL, 15.0, 15.0, 0);
INSERT INTO "runes" VALUES ('Runeword164', 'Wings of Hope', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword165', 'Wisdom', 1.0, 1.0, 2.0, 'D2R Ladder 1', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PulIthEld', 'r21', 'r06', 'r02', NULL, NULL, NULL, 'pierce', NULL, 33.0, 33.0, 'manasteal', NULL, 4.0, 8.0, 'att%', NULL, 15.0, 25.0, 'mana-kill', NULL, 5.0, 5.0, 'nofreeze', NULL, 1.0, 1.0, 'enr', NULL, 10.0, 10.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword166', 'Woe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword167', 'Wonder', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword168', 'Wrath', 1.0, NULL, NULL, 'Previously Ladder Only', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PulLumBerMal', 'r21', 'r17', 'r30', 'r23', NULL, NULL, 'dmg-demon', NULL, 300.0, 300.0, 'dmg-undead', NULL, 250.0, 300.0, 'dmg-ltng', NULL, 41.0, 240.0, 'dmg-mag', NULL, 85.0, 120.0, 'hit-skill', 'Life Tap', 5.0, 10.0, 'hit-skill', 'Decrepify', 30.0, 1.0, 'nofreeze', NULL, 1.0, 1.0, 0);
INSERT INTO "runes" VALUES ('Runeword169', 'Youth', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword170', 'Zephyr', 1.0, NULL, NULL, '109', 'miss', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'OrtEth', 'r09', 'r05', NULL, NULL, NULL, NULL, 'move2', NULL, 25.0, 25.0, 'swing2', NULL, 25.0, 25.0, 'dmg%', NULL, 33.0, 33.0, 'att', NULL, 66.0, 66.0, 'gethit-skill', '240', 7.0, 1.0, 'ac', NULL, 25.0, 25.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword171', 'Hustle (armor)', 1.0, 3.0, NULL, 'D2R Ladder 3', 'tors', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelKoEld', 'r13', 'r18', 'r02', NULL, NULL, NULL, 'move2', NULL, 65.0, 65.0, 'stamdrain', NULL, 35.0, 35.0, 'swing2', NULL, 40.0, 40.0, 'res-all', NULL, 10.0, 10.0, 'oskill', 'Evade', 6.0, 6.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword172', 'Hustle (weapon)', 1.0, 3.0, NULL, 'D2R Ladder 3', 'weap', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelKoEld', 'r13', 'r18', 'r02', NULL, NULL, NULL, 'hit-skill', 'Quickness', 5.0, 1.0, 'swing2', NULL, 10.0, 10.0, 'dmg%', NULL, 180.0, 200.0, 'aura', 'Fanaticism', 1.0, 1.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword173', 'Mosaic', 1.0, 3.0, NULL, 'D2R Ladder 3', 'h2h', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MalGulAmn', 'r23', 'r25', 'r11', NULL, NULL, NULL, 'skilltab', '20', 2.0, 2.0, 'charge-noconsume', NULL, 50.0, 50.0, 'swing2', NULL, 20.0, 20.0, 'dmg%', NULL, 200.0, 250.0, 'extra-fire', NULL, 8.0, 15.0, 'extra-cold', NULL, 8.0, 15.0, 'extra-ltng', NULL, 8.0, 15.0, 0);
INSERT INTO "runes" VALUES ('Runeword174', 'Metamorphosis', 1.0, 3.0, NULL, 'D2R Ladder 3', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'IoChamFal', 'r16', 'r32', 'r19', NULL, NULL, NULL, 'hit-skill', 'Mark of the Bear', 100.0, 1.0, 'hit-skill', 'Mark of the Wolf', 100.0, 1.0, 'skilltab', '16', 5.0, 5.0, 'ac%', NULL, 50.0, 80.0, 'res-all', NULL, 10.0, 10.0, 'crush', NULL, 25.0, 25.0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword175', 'Ground', 1.0, 3.0, NULL, 'D2R Ladder 3', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelIoOrt', 'r13', 'r16', 'r09', NULL, NULL, NULL, 'hp%', NULL, 5.0, 5.0, 'ac%', NULL, 75.0, 100.0, 'res-ltng', NULL, 10.0, 30.0, 'abs-ltng%', NULL, 10.0, 15.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword176', 'Temper', 1.0, 3.0, NULL, 'D2R Ladder 3', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelIoRal', 'r13', 'r16', 'r08', NULL, NULL, NULL, 'hp%', NULL, 5.0, 5.0, 'ac%', NULL, 75.0, 100.0, 'res-fire', NULL, 10.0, 30.0, 'abs-fire%', NULL, 10.0, 15.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword177', 'Hearth', 1.0, 3.0, NULL, 'D2R Ladder 3', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelIoThul', 'r13', 'r16', 'r10', NULL, NULL, NULL, 'hp%', NULL, 5.0, 5.0, 'ac%', NULL, 75.0, 100.0, 'res-cold', NULL, 10.0, 30.0, 'abs-cold%', NULL, 10.0, 15.0, 'nofreeze', NULL, 1.0, 1.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword178', 'Cure', 1.0, 3.0, NULL, 'D2R Ladder 3', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelIoTal', 'r13', 'r16', 'r07', NULL, NULL, NULL, 'hp%', NULL, 5.0, 5.0, 'ac%', NULL, 75.0, 100.0, 'res-pois', NULL, 10.0, 30.0, 'res-pois-len', NULL, 50.0, 50.0, 'aura', 'Cleansing', 1.0, 1.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO "runes" VALUES ('Runeword179', 'Bulwark', 1.0, 3.0, NULL, 'D2R Ladder 3', 'helm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShaelIoSol', 'r13', 'r16', 'r12', NULL, NULL, NULL, 'hp%', NULL, 5.0, 5.0, 'ac%', NULL, 75.0, 100.0, 'red-dmg%', NULL, 10.0, 15.0, 'regen', NULL, 30.0, 30.0, 'lifesteal', NULL, 4.0, 6.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);

PRAGMA foreign_keys = true;
